from __future__ import annotations

import argparse
import json
import os
import hashlib
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable


DEFAULT_PROVIDER_IDS = ("claude-code", "gemini", "cursor", "windsurf")
SKILL_NAME = "openyggdrasil"
SKILL_DESCRIPTION = (
    "Attaches the current provider session to the shared OpenYggdrasil memory "
    "forest when the session needs durable memory, attachment repair, or "
    "session-bound inbox access."
)
REFERENCE_PATHS = {
    "canonical_skill": Path("SKILL.md"),
    "cold_start_healthcheck": Path("runtime/attachments/provider_cold_start_healthcheck.py"),
    "validator": Path("runtime/attachments/validate_attachment.py"),
    "repair": Path("runtime/attachments/repair_attachment.py"),
}
DEPLOY_TARGETS = {
    "claude-code": Path(".claude/skills/openyggdrasil/SKILL.md"),
    "gemini": Path("GEMINI.md"),
    "cursor": Path(".cursor/rules/openyggdrasil.mdc"),
    "windsurf": Path(".windsurf/skills/openyggdrasil/SKILL.md"),
}
DEPLOY_MANIFEST_PATH = Path(".yggdrasil/deploy/provider-skill-deploy-manifest.json")


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


@dataclass(frozen=True)
class DeployRecord:
    provider_id: str
    destination: Path
    status: str


def _canonical_source_paths(workspace_root: Path) -> list[Path]:
    paths = {workspace_root / "SKILL.md"}
    paths.update(workspace_root / value for value in REFERENCE_PATHS.values())
    return sorted(paths)


def _validate_source_tree(workspace_root: Path) -> None:
    missing = [str(path) for path in _canonical_source_paths(workspace_root) if not path.exists()]
    if missing:
        raise FileNotFoundError(
            "workspace root is missing canonical skill source files: " + ", ".join(missing)
        )


def _file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _relative_reference(destination: Path, target: Path) -> str:
    return Path(os.path.relpath(target, destination.parent)).as_posix()


def _reference_lines(workspace_root: Path, destination: Path) -> list[str]:
    lines = []
    for key, relative_path in REFERENCE_PATHS.items():
        target = workspace_root / relative_path
        lines.append(f"- {key}: `{_relative_reference(destination, target)}`")
    return lines


def _render_skill_markdown(*, workspace_root: Path, provider_id: str, destination: Path) -> str:
    reference_lines = "\n".join(_reference_lines(workspace_root, destination))
    return f"""---
name: {SKILL_NAME}
description: {SKILL_DESCRIPTION}
---

# OpenYggdrasil

This is a provider-native deployed view of the canonical OpenYggdrasil skill.

Use this skill when the current session needs:

- workspace-local attachment bootstrap
- cold-start environment healthcheck
- attachment repair
- session-bound inbox access
- durable memory without collapsing provenance

Core rules:

- stay in the current workspace
- run the cold-start healthcheck on first install or when forced by the operator
- preserve provider/profile/session boundaries
- never use a global inbox
- keep `vault/` canonical
- prefer symbolic provenance over raw transcript copying

Canonical references in this workspace:

{reference_lines}

This file is generated for `{provider_id}` from the canonical workspace source.
Do not edit this file directly.
"""


def _render_gemini_markdown(*, workspace_root: Path, destination: Path) -> str:
    reference_lines = "\n".join(_reference_lines(workspace_root, destination))
    return f"""# OpenYggdrasil

OpenYggdrasil attaches the current provider session to the shared memory forest
through explicit workspace-local contracts.

Use it when the current session needs durable memory, attachment repair, or
session-bound inbox access.

Core rules:

- stay in the current workspace
- run the cold-start healthcheck on first install or when forced by the operator
- preserve provider/profile/session boundaries
- never use a global inbox
- keep `vault/` canonical

Canonical references in this workspace:

{reference_lines}

This file is generated from the canonical workspace skill source.
"""


def _render_cursor_rule(*, workspace_root: Path, destination: Path) -> str:
    reference_lines = "\n".join(_reference_lines(workspace_root, destination))
    return f"""---
description: {SKILL_DESCRIPTION}
alwaysApply: false
---

# OpenYggdrasil

When the current session needs durable memory, attachment repair, or
session-bound inbox access, use OpenYggdrasil instead of inventing a new memory
surface.

Rules:

- stay in the current workspace
- run the cold-start healthcheck on first install or when forced by the operator
- preserve provider/profile/session boundaries
- never use a global inbox
- keep `vault/` canonical

Canonical references in this workspace:

{reference_lines}

This file is generated from the canonical workspace skill source.
"""


def _render_content(*, workspace_root: Path, provider_id: str, destination: Path) -> str:
    if provider_id == "gemini":
        return _render_gemini_markdown(workspace_root=workspace_root, destination=destination)
    if provider_id == "cursor":
        return _render_cursor_rule(workspace_root=workspace_root, destination=destination)
    return _render_skill_markdown(
        workspace_root=workspace_root,
        provider_id=provider_id,
        destination=destination,
    )


def manifest_path_for(workspace_root: Path) -> Path:
    return workspace_root / DEPLOY_MANIFEST_PATH


def _build_manifest(
    *,
    workspace_root: Path,
    rows: list[dict[str, str]],
) -> dict[str, object]:
    source_hashes = {
        str(path.relative_to(workspace_root).as_posix()): _file_sha256(path)
        for path in _canonical_source_paths(workspace_root)
    }
    return {
        "schema_version": "provider_skill_deploy_manifest.v1",
        "generated_at": utc_now_iso(),
        "workspace_root": str(workspace_root),
        "source_hashes": source_hashes,
        "deployments": rows,
    }


def build_deploy_plan(
    *,
    workspace_root: Path,
    provider_ids: Iterable[str] = DEFAULT_PROVIDER_IDS,
) -> list[DeployRecord]:
    plan: list[DeployRecord] = []
    for provider_id in provider_ids:
        if provider_id not in DEPLOY_TARGETS:
            raise ValueError(f"unsupported provider for file deployment: {provider_id}")
        plan.append(
            DeployRecord(
                provider_id=provider_id,
                destination=workspace_root / DEPLOY_TARGETS[provider_id],
                status="planned",
            )
        )
    return plan


def deploy_skill_surfaces(
    *,
    workspace_root: Path,
    provider_ids: Iterable[str] = DEFAULT_PROVIDER_IDS,
    dry_run: bool = False,
) -> list[dict[str, str]]:
    workspace_root = workspace_root.resolve()
    _validate_source_tree(workspace_root)
    plan = build_deploy_plan(workspace_root=workspace_root, provider_ids=provider_ids)
    rows: list[dict[str, str]] = []
    for record in plan:
        row = {
            "provider_id": record.provider_id,
            "destination": str(record.destination),
            "status": "dry_run" if dry_run else "written",
        }
        if not dry_run:
            record.destination.parent.mkdir(parents=True, exist_ok=True)
            record.destination.write_text(
                _render_content(
                    workspace_root=workspace_root,
                    provider_id=record.provider_id,
                    destination=record.destination,
                ),
                encoding="utf-8",
            )
        rows.append(row)
    if not dry_run:
        manifest_path = manifest_path_for(workspace_root)
        manifest_path.parent.mkdir(parents=True, exist_ok=True)
        manifest_path.write_text(
            json.dumps(_build_manifest(workspace_root=workspace_root, rows=rows), ensure_ascii=False, indent=2)
            + "\n",
            encoding="utf-8",
        )
    return rows


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Deploy provider-native OpenYggdrasil skill surfaces.")
    parser.add_argument(
        "--workspace-root",
        type=Path,
        default=Path(__file__).resolve().parents[2],
        help="Workspace root that owns the canonical skill source.",
    )
    parser.add_argument(
        "--providers",
        nargs="*",
        default=list(DEFAULT_PROVIDER_IDS),
        help="Provider ids to deploy. Supported: claude-code gemini cursor windsurf",
    )
    parser.add_argument("--dry-run", action="store_true", help="Report what would be written.")
    parser.add_argument("--json", action="store_true", help="Emit a JSON report.")
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    report = deploy_skill_surfaces(
        workspace_root=args.workspace_root,
        provider_ids=args.providers,
        dry_run=args.dry_run,
    )
    if args.json:
        print(json.dumps(report, ensure_ascii=False, indent=2))
    else:
        for row in report:
            print(f"{row['status']}: {row['provider_id']} -> {row['destination']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
